import MovieCard from "../components/Movies/movie-card";

const Home = () => {
  const playing = {
    dates: {
      maximum: "2024-08-28",
      minimum: "2024-07-17",
    },
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
        genre_ids: [28, 35, 878],
        id: 533535,
        original_language: "en",
        original_title: "Deadpool & Wolverine",
        overview:
          "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
        popularity: 5382.642,
        poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        release_date: "2024-07-24",
        title: "Deadpool & Wolverine",
        video: false,
        vote_average: 7.756,
        vote_count: 2222,
      },
      {
        adult: false,
        backdrop_path: "/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg",
        genre_ids: [16, 10751, 12, 35],
        id: 1022789,
        original_language: "en",
        original_title: "Inside Out 2",
        overview:
          "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
        popularity: 2866.31,
        poster_path: "/xeqXXTE1Cd3qNaAEOT6qbhhCsgJ.jpg",
        release_date: "2024-06-11",
        title: "Inside Out 2",
        video: false,
        vote_average: 7.661,
        vote_count: 2846,
      },
      {
        adult: false,
        backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
        genre_ids: [16, 10751, 35, 28],
        id: 519182,
        original_language: "en",
        original_title: "Despicable Me 4",
        overview:
          "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
        popularity: 2065.339,
        poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
        release_date: "2024-06-20",
        title: "Despicable Me 4",
        video: false,
        vote_average: 7.3,
        vote_count: 1193,
      },
      {
        adult: false,
        backdrop_path: "/58D6ZAvOKxlHjyX9S8qNKSBE9Y.jpg",
        genre_ids: [28, 12, 18, 53],
        id: 718821,
        original_language: "en",
        original_title: "Twisters",
        overview:
          "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
        popularity: 1983.441,
        poster_path: "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
        release_date: "2024-07-10",
        title: "Twisters",
        video: false,
        vote_average: 7.045,
        vote_count: 999,
      },
      {
        adult: false,
        backdrop_path: "/pzFbYJfqGKlGxOsDIIsUi6YxVQ.jpg",
        genre_ids: [28, 35, 878],
        id: 1094138,
        original_language: "en",
        original_title: "Jackpot!",
        overview:
          "In the near future, a 'Grand Lottery' has been established - the catch: kill the winner before sundown to legally claim their multi-billion dollar jackpot. When Katie Kim mistakenly finds herself with the winning ticket, she reluctantly joins forces with amateur lottery protection agent Noel Cassidy who must get her to sundown in exchange for a piece of her prize.",
        popularity: 1490.219,
        poster_path: "/wWWlclyWf4PLq9hOf8X5joVEJ6r.jpg",
        release_date: "2024-08-13",
        title: "Jackpot!",
        video: false,
        vote_average: 6.504,
        vote_count: 250,
      },
      {
        adult: false,
        backdrop_path: "/4ft6TR9wA6bra0RLL6G7JFDQ5t1.jpg",
        genre_ids: [28, 35],
        id: 704239,
        original_language: "en",
        original_title: "The Union",
        overview:
          "A New Jersey construction worker goes from regular guy to aspiring spy when his long-lost high school sweetheart recruits him for an espionage mission.",
        popularity: 1372.665,
        poster_path: "/d9CTnTHip1RbVi2OQbA2LJJQAGI.jpg",
        release_date: "2024-08-15",
        title: "The Union",
        video: false,
        vote_average: 6.316,
        vote_count: 318,
      },
      {
        adult: false,
        backdrop_path: "/okVLmXL5y18dfN2R4ufMZEGaeCd.jpg",
        genre_ids: [28, 80],
        id: 1160018,
        original_language: "hi",
        original_title: "Kill",
        overview:
          "When an army commando finds out his true love is engaged against her will, he boards a New Dehli-bound train in a daring quest to derail the arranged marriage. But when a gang of knife-wielding thieves begin to terrorize innocent passengers on his train, the commando takes them on himself in a death-defying kill-spree to save those around him — turning what should have been a typical commute into an adrenaline-fueled thrill ride.",
        popularity: 1342.031,
        poster_path: "/m2zXTuNPkywdYLyWlVyJZW2QOJH.jpg",
        release_date: "2024-07-03",
        title: "Kill",
        video: false,
        vote_average: 7.0,
        vote_count: 81,
      },
      {
        adult: false,
        backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
        genre_ids: [27, 878],
        id: 945961,
        original_language: "en",
        original_title: "Alien: Romulus",
        overview:
          "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
        popularity: 1300.216,
        poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
        release_date: "2024-08-13",
        title: "Alien: Romulus",
        video: false,
        vote_average: 7.3,
        vote_count: 539,
      },
      {
        adult: false,
        backdrop_path: "/9BQqngPfwpeAfK7c2H3cwIFWIVR.jpg",
        genre_ids: [10749, 18],
        id: 1079091,
        original_language: "en",
        original_title: "It Ends with Us",
        overview:
          "Lily Bloom overcomes a traumatic childhood to embark on a new life in Boston and chase a lifelong dream of opening her own business. A chance meeting with charming neurosurgeon Ryle Kincaid sparks an intense connection, but as the two fall deeply in love, Lily begins to see sides of Ryle that remind her of her parents' relationship.",
        popularity: 1200.719,
        poster_path: "/AjV6jFJ2YFIluYo4GQf13AA1tqu.jpg",
        release_date: "2024-08-07",
        title: "It Ends with Us",
        video: false,
        vote_average: 7.0,
        vote_count: 155,
      },
      {
        adult: false,
        backdrop_path: "/2MJIfQDA9orY3uVSnzExogbdhH6.jpg",
        genre_ids: [16, 35, 12, 10751],
        id: 831815,
        original_language: "en",
        original_title: "Saving Bikini Bottom: The Sandy Cheeks Movie",
        overview:
          "When Bikini Bottom is scooped from the ocean, scientific squirrel Sandy Cheeks and her pal SpongeBob SquarePants saddle up for Texas to save their town.",
        popularity: 997.015,
        poster_path: "/30YnfZdMNIV7noWLdvmcJS0cbnQ.jpg",
        release_date: "2024-08-01",
        title: "Saving Bikini Bottom: The Sandy Cheeks Movie",
        video: false,
        vote_average: 6.388,
        vote_count: 161,
      },
      {
        adult: false,
        backdrop_path: "/h9YlRHAZWOWtGonllmj6JJg1FrE.jpg",
        genre_ids: [28, 12, 16, 10751, 14],
        id: 588648,
        original_language: "zh",
        original_title: "Dragonkeeper",
        overview:
          "Set in Han Imperial China, the plot follows the adventures of enslaved girl Ping with ancient dragon Long Danzi. Dragons had been banished from the kingdom. Ping, an orphan, finds one of the last remaining dragon eggs. Palace guards force Ping to run away in order to return the dragon egg to the ocean and save all dragons from extinction. Ping discovers that she is a true Dragonkeeper.",
        popularity: 969.9,
        poster_path: "/ggZGnJLzO3BTu7ysuuIzou3Oex5.jpg",
        release_date: "2024-04-11",
        title: "Dragonkeeper",
        video: false,
        vote_average: 7.2,
        vote_count: 42,
      },
      {
        adult: false,
        backdrop_path: "/1wP1phHo2CROOqzv7Azs0MT5esU.jpg",
        genre_ids: [16, 35, 10751, 12, 28],
        id: 748783,
        original_language: "en",
        original_title: "The Garfield Movie",
        overview:
          "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
        popularity: 813.181,
        poster_path: "/xYduFGuch9OwbCOEUiamml18ZoB.jpg",
        release_date: "2024-04-30",
        title: "The Garfield Movie",
        video: false,
        vote_average: 7.184,
        vote_count: 812,
      },
      {
        adult: false,
        backdrop_path: "/yhEu41kat5sZ5QhCdZnh3Vypu5V.jpg",
        genre_ids: [27, 53, 35],
        id: 1225377,
        original_language: "en",
        original_title: "The Mouse Trap",
        overview:
          "It's Alex's 21st Birthday, but she's stuck at the amusement arcade on a late shift so her friends decide to surprise her, but a masked killer dressed as Mickey Mouse decides to play a game of his own with them which she must survive.",
        popularity: 596.976,
        poster_path: "/3ovFaFeojLFIl5ClqhtgYMDS8sE.jpg",
        release_date: "2024-08-23",
        title: "The Mouse Trap",
        video: false,
        vote_average: 3.4,
        vote_count: 7,
      },
      {
        adult: false,
        backdrop_path: "/aA5B2OsN6rccwnhn8TEG4m4V3jI.jpg",
        genre_ids: [28, 35, 80],
        id: 1059064,
        original_language: "en",
        original_title: "The Instigators",
        overview:
          "Rory and Cobby are unlikely partners thrown together for a heist. But when it goes awry, they team up to outrun police, backward bureaucrats, and a vengeful crime boss.",
        popularity: 745.646,
        poster_path: "/pIz9csYn1yjrzQi0BuBZNJrTMi0.jpg",
        release_date: "2024-08-02",
        title: "The Instigators",
        video: false,
        vote_average: 6.341,
        vote_count: 208,
      },
      {
        adult: false,
        backdrop_path: "/1KJtjg3MQFnrfd7NXfs11z4HLwD.jpg",
        genre_ids: [53, 27],
        id: 804616,
        original_language: "en",
        original_title: "Something in the Water",
        overview:
          "Reunited at an exotic destination wedding, five girlfriends decide to rent a boat to spend a day together along the paradise-like coast. Their friendship is put to the ultimate test when they find themselves stranded in open water fighting for their lives against sharks and mother nature as they desperately try to survive.",
        popularity: 746.351,
        poster_path: "/1iWGGxHEwswZGvPSoMZlLFf0PNq.jpg",
        release_date: "2024-03-22",
        title: "Something in the Water",
        video: false,
        vote_average: 5.976,
        vote_count: 106,
      },
      {
        adult: false,
        backdrop_path: "/QflfyU07MiQXSqTUCmG9Xfq0Ws.jpg",
        genre_ids: [28, 18, 10749],
        id: 1281826,
        original_language: "en",
        original_title: "One Fast Move",
        overview:
          "A dishonorably discharged soldier seeks out his estranged father to help him pursue his dream of becoming a professional motorcycle racer. While training, he meets a small-town, aspiring singer and a motorcycle shop owner who begin to break down the walls his father's absence had built up.",
        popularity: 733.633,
        poster_path: "/hdBUjfbdr1ymS0kycAT7qguOmWA.jpg",
        release_date: "2024-08-07",
        title: "One Fast Move",
        video: false,
        vote_average: 6.9,
        vote_count: 93,
      },
      {
        adult: false,
        backdrop_path: "/lyEuje8cKjbWliYUGrOaoHVmc1R.jpg",
        genre_ids: [28, 35, 12],
        id: 1002088,
        original_language: "ko",
        original_title: "크로스",
        overview:
          "In the ultimate test of marriage, an agent-turned-househusband gets tangled in a perilous mission with his detective wife, who's clueless about his past.",
        popularity: 629.066,
        poster_path: "/aE9WqOApdRYsowsGE0118dyA4c9.jpg",
        release_date: "2024-08-05",
        title: "Mission: Cross",
        video: false,
        vote_average: 7.078,
        vote_count: 58,
      },
      {
        adult: false,
        backdrop_path: "/zB0g0VaRKHfRrvBT4ouHK5W967W.jpg",
        genre_ids: [10749, 35],
        id: 956842,
        original_language: "en",
        original_title: "Fly Me to the Moon",
        overview:
          "Sparks fly in all directions as marketing maven Kelly Jones, brought in to fix NASA's public image, wreaks havoc on Apollo 11 launch director Cole Davis' already difficult task of putting a man on the moon. When the White House deems the mission too important to fail, Jones is directed to stage a fake moon landing as backup, and the countdown truly begins.",
        popularity: 495.551,
        poster_path: "/gjk8YdXpItoC1in53FCrZMFIuBx.jpg",
        release_date: "2024-07-10",
        title: "Fly Me to the Moon",
        video: false,
        vote_average: 7.072,
        vote_count: 314,
      },
      {
        adult: false,
        backdrop_path: "/xYyPLClpJiA5pq687pGjRel5qgf.jpg",
        genre_ids: [28, 53],
        id: 1064375,
        original_language: "en",
        original_title: "Paradox Effect",
        overview:
          "An innocent woman is forced to confront a dangerous kingpin who has kidnapped her young daughter and is holding her for ransom. She teams up with a corrupt Interpol agent, whose son is also being held hostage, to rip off various criminals to raise the ransom to save their offspring. Together they have one hour to save their families from the wrath of bigwig.",
        popularity: 543.256,
        poster_path: "/koJFEW997sLjpu4e7wmFioA2mhL.jpg",
        release_date: "2024-06-27",
        title: "Paradox Effect",
        video: false,
        vote_average: 6.4,
        vote_count: 18,
      },
      {
        adult: false,
        backdrop_path: "/c3rwwFFVbkyEI6wPtpPd9lvovPW.jpg",
        genre_ids: [28, 36],
        id: 1311550,
        original_language: "en",
        original_title: "House of Ga'a",
        overview:
          "At the height of the Oyo Empire, the ferocious Bashorun Ga'a became more powerful than the kings he enthroned, only to be undone by his own blood.",
        popularity: 532.119,
        poster_path: "/6yK9hmS641NMwRkR1wWAALWI34t.jpg",
        release_date: "2024-07-26",
        title: "House of Ga'a",
        video: false,
        vote_average: 5.89,
        vote_count: 41,
      },
    ],
    total_pages: 188,
    total_results: 3755,
  };

  const top = {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/avedvodAZUcwqevBfm8p4G2NziQ.jpg",
        genre_ids: [18, 80],
        id: 278,
        original_language: "en",
        original_title: "The Shawshank Redemption",
        overview:
          "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
        popularity: 126.784,
        poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
        release_date: "1994-09-23",
        title: "The Shawshank Redemption",
        video: false,
        vote_average: 8.705,
        vote_count: 26683,
      },
      {
        adult: false,
        backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
        genre_ids: [18, 80],
        id: 238,
        original_language: "en",
        original_title: "The Godfather",
        overview:
          "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
        popularity: 314.507,
        poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        release_date: "1972-03-14",
        title: "The Godfather",
        video: false,
        vote_average: 8.691,
        vote_count: 20243,
      },
      {
        adult: false,
        backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
        genre_ids: [18, 80],
        id: 240,
        original_language: "en",
        original_title: "The Godfather Part II",
        overview:
          "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
        popularity: 98.358,
        poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
        release_date: "1974-12-20",
        title: "The Godfather Part II",
        video: false,
        vote_average: 8.574,
        vote_count: 12211,
      },
      {
        adult: false,
        backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
        genre_ids: [18, 36, 10752],
        id: 424,
        original_language: "en",
        original_title: "Schindler's List",
        overview:
          "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
        popularity: 90.134,
        poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
        release_date: "1993-12-15",
        title: "Schindler's List",
        video: false,
        vote_average: 8.565,
        vote_count: 15623,
      },
      {
        adult: false,
        backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
        genre_ids: [18],
        id: 389,
        original_language: "en",
        original_title: "12 Angry Men",
        overview:
          "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
        popularity: 45.54,
        poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
        release_date: "1957-04-10",
        title: "12 Angry Men",
        video: false,
        vote_average: 8.544,
        vote_count: 8460,
      },
      {
        adult: false,
        backdrop_path: "/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg",
        genre_ids: [16, 10751, 14],
        id: 129,
        original_language: "ja",
        original_title: "千と千尋の神隠し",
        overview:
          "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
        popularity: 104.386,
        poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
        release_date: "2001-07-20",
        title: "Spirited Away",
        video: false,
        vote_average: 8.536,
        vote_count: 16249,
      },
      {
        adult: false,
        backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
        genre_ids: [35, 18, 10749],
        id: 19404,
        original_language: "hi",
        original_title: "दिलवाले दुल्हनिया ले जायेंगे",
        overview:
          "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
        popularity: 35.751,
        poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
        release_date: "1995-10-20",
        title: "Dilwale Dulhania Le Jayenge",
        video: false,
        vote_average: 8.534,
        vote_count: 4417,
      },
      {
        adult: false,
        backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
        genre_ids: [18, 28, 80, 53],
        id: 155,
        original_language: "en",
        original_title: "The Dark Knight",
        overview:
          "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
        popularity: 146.483,
        poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        release_date: "2008-07-16",
        title: "The Dark Knight",
        video: false,
        vote_average: 8.516,
        vote_count: 32418,
      },
      {
        adult: false,
        backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
        genre_ids: [14, 18, 80],
        id: 497,
        original_language: "en",
        original_title: "The Green Mile",
        overview:
          "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
        popularity: 84.99,
        poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
        release_date: "1999-12-10",
        title: "The Green Mile",
        video: false,
        vote_average: 8.5,
        vote_count: 17121,
      },
      {
        adult: false,
        backdrop_path: "/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg",
        genre_ids: [35, 53, 18],
        id: 496243,
        original_language: "ko",
        original_title: "기생충",
        overview:
          "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
        popularity: 73.689,
        poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        release_date: "2019-05-30",
        title: "Parasite",
        video: false,
        vote_average: 8.506,
        vote_count: 17928,
      },
      {
        adult: false,
        backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
        genre_ids: [53, 80],
        id: 680,
        original_language: "en",
        original_title: "Pulp Fiction",
        overview:
          "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
        popularity: 109.045,
        poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        release_date: "1994-09-10",
        title: "Pulp Fiction",
        video: false,
        vote_average: 8.488,
        vote_count: 27539,
      },
      {
        adult: false,
        backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
        genre_ids: [16, 10749, 18],
        id: 372058,
        original_language: "ja",
        original_title: "君の名は。",
        overview:
          "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
        popularity: 75.125,
        poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
        release_date: "2016-08-26",
        title: "Your Name.",
        video: false,
        vote_average: 8.487,
        vote_count: 11206,
      },
      {
        adult: false,
        backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
        genre_ids: [12, 14, 28],
        id: 122,
        original_language: "en",
        original_title: "The Lord of the Rings: The Return of the King",
        overview:
          "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
        popularity: 126.868,
        poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
        release_date: "2003-12-17",
        title: "The Lord of the Rings: The Return of the King",
        video: false,
        vote_average: 8.481,
        vote_count: 23802,
      },
      {
        adult: false,
        backdrop_path: "/ghgfzbEV7kbpbi1O8eIILKVXEA8.jpg",
        genre_ids: [35, 18, 10749],
        id: 13,
        original_language: "en",
        original_title: "Forrest Gump",
        overview:
          "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
        popularity: 106.479,
        poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
        release_date: "1994-06-23",
        title: "Forrest Gump",
        video: false,
        vote_average: 8.474,
        vote_count: 27057,
      },
      {
        adult: false,
        backdrop_path: "/i9qxG4UVgfX4AdMGnfRzMYEowLQ.jpg",
        genre_ids: [12, 36, 28, 18, 10749, 53],
        id: 1084736,
        original_language: "fr",
        original_title: "Le Comte de Monte-Cristo",
        overview:
          "Edmond Dantes becomes the target of a sinister plot and is arrested on his wedding day for a crime he did not commit. After 14 years in the island prison of Château d’If, he manages a daring escape. Now rich beyond his dreams, he assumes the identity of the Count of Monte-Cristo and exacts his revenge on the three men who betrayed him.",
        popularity: 105.779,
        poster_path: "/aHRUsFln97FlIdsvYKFT3z5ubYE.jpg",
        release_date: "2024-06-28",
        title: "The Count of Monte-Cristo",
        video: false,
        vote_average: 8.472,
        vote_count: 463,
      },
      {
        adult: false,
        backdrop_path: "/7TF4p86ZafnxFuNqWdhpHXFO244.jpg",
        genre_ids: [18, 80],
        id: 769,
        original_language: "en",
        original_title: "GoodFellas",
        overview:
          "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
        popularity: 81.274,
        poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
        release_date: "1990-09-12",
        title: "GoodFellas",
        video: false,
        vote_average: 8.5,
        vote_count: 12647,
      },
      {
        adult: false,
        backdrop_path: "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
        genre_ids: [28, 18],
        id: 346,
        original_language: "ja",
        original_title: "七人の侍",
        overview:
          "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
        popularity: 44.302,
        poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
        release_date: "1954-04-26",
        title: "Seven Samurai",
        video: false,
        vote_average: 8.5,
        vote_count: 3587,
      },
      {
        adult: false,
        backdrop_path: "/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg",
        genre_ids: [10751, 18],
        id: 667257,
        original_language: "es",
        original_title: "Cosas imposibles",
        overview:
          "After the death of her abusive husband, Matilde finds her new best friend in Miguel, her young, insecure, and disoriented neighbor.",
        popularity: 16.385,
        poster_path: "/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg",
        release_date: "2021-06-17",
        title: "Impossible Things",
        video: false,
        vote_average: 8.462,
        vote_count: 381,
      },
      {
        adult: false,
        backdrop_path: "/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg",
        genre_ids: [37],
        id: 429,
        original_language: "it",
        original_title: "Il buono, il brutto, il cattivo",
        overview:
          "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
        popularity: 69.605,
        poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
        release_date: "1966-12-22",
        title: "The Good, the Bad and the Ugly",
        video: false,
        vote_average: 8.462,
        vote_count: 8449,
      },
      {
        adult: false,
        backdrop_path: "/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg",
        genre_ids: [16, 18, 10752],
        id: 12477,
        original_language: "ja",
        original_title: "火垂るの墓",
        overview:
          "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
        popularity: 0.048,
        poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
        release_date: "1988-04-16",
        title: "Grave of the Fireflies",
        video: false,
        vote_average: 8.457,
        vote_count: 5370,
      },
    ],
    total_pages: 480,
    total_results: 9583,
  };
  return (
    <div className="px-20 pt-10">
      <h2 className="text-white font-semibold text-5xl mb-4">Now Playing</h2>
      <div className="flex overflow-x-scroll gap-7 scrollbar mb-12">
        {playing.results.map((movie: any) => (
          <MovieCard movie={movie} />
        ))}
      </div>
      <h2 className="text-white font-semibold text-5xl mb-4">Top Rated</h2>
      <div className="grid grid-cols-6 gap-7">
        {top.results.map((movie: any) => (
          <MovieCard movie={movie} />
        ))}
      </div>
    </div>
  );
};

export default Home;
